### PR TITLE
wierd logs?

### PR DESCRIPTION
**Pull request by StoneyDSP**
Some crafty admirer (?) appears to have taken an interest in our web page contents. While this in itself is quite flattering, the insinuation that I've used a Wordpress theme is not; they should be quite assured by simply looking at the source code right here on Git. 

For any interested parties:

- I used <a href="https://github.com/christianschlosser/doxygen">doxygen</a> to generate HTML documentation in several of my C++-based project repositories. Doxgen converts formatted code comments into several output formats, such as HTML, TeX, MAN pages, etc... several of my favourite frameworks and libraries use it in their codebase, and this familiarity is something I and I think many others benefit from.

- Using doxygen's CLI tools, I had it spit out its' standard HTML header and footer templates (fragments), and its' default CSS stylesheet. I then made some changes to the contents of these templates, and configured the doxygen projects to use these custom files in place of the default behaviour (all explained in ```doxygen --help```).

- The primary changes were simply fleshing out the HTML head with meta tags and making sure the links for resources like javascript and CSS files were all pointing to an *absolute path*, thus making them somewhat portable within the project. I also took my (deprecating) <a href="https://github.com/StoneyDSP/stoney-css">stoney-css</a> source code and planted all of that into the HTML as the *base* CSS, using CSS5 layers; the doxygen-generated CSS was then *appended* to my custom CSS framework, which provides nicely resizeable text, my favourite embedded font (Cascadia, from VSCode!), a bunch of sane defaults, and just some user-agent handling and debugging I've picked up from web dev'ing. So, my custom CSS initializes and sets up the page styles, and the doxygen CSS sits on top of that, over-riding some selectors as necessary (and that's where the magic of CSS layers comes in helpful!)

- At the moment, I've duplicated the landing page for the already-published projects and placed these duplicate html files in the project root folder under their own names, so they are accessible as simple and short page links: "stoneydsp.com/ubento.html" and so forth. However, each project sub-page is actually hosted over in it's own git repo, which Git Pages serves up nicely and automagically: "stoneydsp.github.io/UBento/index.html". I am still considering the best approach for project sub-pages, as the former option (serving every page from this repo) would get very unwieldy, very quickly, BUT enables us to localize *all* resources, including nav and search bars, analytic tools, and such forth, into one single location - the sane thing to do!? On the other hand, staying with the GitHub Pages split server approach means we can (theoretically) keep each sup-page in sync with it's own codebase far easier, not to mention version controlling, and such forth, with each sub-project essentially carrying all of it's own footprint, and this central page mostly serving links to those other hosted pages (and their subpages within). This comes at the expense of having centralized resources for items like the search bar, which requires a populated list of search terms and absolute paths - from the served root folder - in order to function. Essentially, we can still use the search bar this way, but it will only be able to search from each sub-project downwards; No cross-referencing would be possible to, say, link the same namespace between two or more sub-projects. Under the current implementation, the workload of creating a centralized search function from multiple unrelated doxygen projects appears to be unworkable due to sheer volume.

- I have locally tested and created a set of doxygen template files and corresponding config to produce '\*.vue' files with populated 'template' tags. Basically, everything that gets generated that would usually be a HTML file on output, comes out with the '.vue' extension. The header template is simply an opening template tag and an opening div tag, both left un-closed here. The footer template contains the closing div/template tags, and is followed by a set of script and style tags, as per .vue files. All of this output goes into the 'pages' directory of the root folder, and then we just use the usual layout techniques to join them together. It works far better with Nuxt.Js doing the glue and the routing, but I am unsure at the moment how best to override the generate anchor tags to use NuxtLinks instead. Again, that could easily be far more work than it's worth - the point in this exercise is using doxygen to extract the useful content into HTML form, and what it does out of the box is perfectly fine.

- I will expand to include most/all of my worthwhile projects, once I have the method and overall theme etc locked in...

### CODE REVIEW

**Comment by StoneyDSP** [comment]
To add: 

- I will probably/possibly make a quick project out of the doxygen/nuxt stuff I've described above, depending on progress as well as external factors (speak with the dev?)

**Comment by StoneyDSP** [comment]
Addendum 2:

- Thanks to <a href="https://github.com/anuraghazra/github-readme-stats">anuraghazra</a> for the GitHub stats cards!

**Comment by StoneyDSP** [comment]
This issue has been persisting.

Initially, the request switched from a list of directories that one might find in a Wordpress-powered site (which, again, this *isn't*), to a GET request at the address ```stoneydsp.com/wp-login.php``` . This fired once or twice between this initial PR and yesterday.

This afternoon, we had a new GET request...

```stoneydsp.com/.git/config```

I mean yeah good luck with that. 

Unbeknownst to them perhaps, I can already see where the request is coming from.

**Comment by StoneyDSP** [comment]
All the below have been added to the ignore list. Looks like Google Analytics/Tag Manager picked up their IP as well, and if accurate, can't say I'm too surprised about. Police might be, though...

```
"TimeUTC","timestampInMs","requestPath","requestMethod","responseStatusCode","requestId","requestUserAgent","level","environment","branch","vercelCache","type","function","host","deploymentDomain","deploymentId","lambdaDurationInMs","lambdaRegion","lambdaMaxMemoryUsed","lambdaMemorySize","message","projectId","projectName"
"2023-09-23 13:31:37",1695475897000,"edge.stoneydsp.com/","GET",308,"c7djv-1695475897116-5b01adeeefe3","['Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36']","info","production","main","MISS","request","/","edge.stoneydsp.com","edge-n4snf8sov-stoneydsp.vercel.app","dpl_GbUnQUKgSdjoHbqd7aeBWj8yR2wX",0,"-",-1,0,"-","prj_bT56uU33xTH0U7kWw3rwu1lB2Ivj","edge"
"2023-09-23 13:30:58",1695475858000,"www.edge.stoneydsp.com/.git/config","GET",308,"kzwwq-1695475858997-e5df1072431d","['Mozilla/5.0 (Linux; Android 12; M2102J20SG) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.61 Mobile Safari/537.36']","info","production","main","MISS","request","/.git/config","www.edge.stoneydsp.com","edge-n4snf8sov-stoneydsp.vercel.app","dpl_GbUnQUKgSdjoHbqd7aeBWj8yR2wX",0,"-",-1,0,"-","prj_bT56uU33xTH0U7kWw3rwu1lB2Ivj","edge"
"2023-09-23 13:30:46",1695475846000,"edge.stoneydsp.com/","HEAD",308,"28lr4-1695475846677-1a74f87e5b73","['Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36']","info","production","main","MISS","request","/","edge.stoneydsp.com","edge-n4snf8sov-stoneydsp.vercel.app","dpl_GbUnQUKgSdjoHbqd7aeBWj8yR2wX",0,"-",-1,0,"-","prj_bT56uU33xTH0U7kWw3rwu1lB2Ivj","edge"
"2023-09-23 13:30:40",1695475840000,"edge.stoneydsp.com/","GET",308,"gtk7j-1695475840577-6301f4f20411","['Go-http-client/1.1']","info","production","main","MISS","request","/","edge.stoneydsp.com","edge-n4snf8sov-stoneydsp.vercel.app","dpl_GbUnQUKgSdjoHbqd7aeBWj8yR2wX",0,"-",-1,0,"-","prj_bT56uU33xTH0U7kWw3rwu1lB2Ivj","edge"
"2023-09-23 13:30:40",1695475840000,"edge.stoneydsp.com/","GET",308,"f96kr-1695475840281-dfbb4f43a37a","['Go-http-client/1.1']","info","production","main","MISS","request","/","edge.stoneydsp.com","edge-n4snf8sov-stoneydsp.vercel.app","dpl_GbUnQUKgSdjoHbqd7aeBWj8yR2wX",0,"-",-1,0,"-","prj_bT56uU33xTH0U7kWw3rwu1lB2Ivj","edge"
"2023-09-23 13:30:05",1695475805000,"www.edge.stoneydsp.com/.git/config","GET",308,"8fzj7-1695475805169-c806bb518196","['Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36 Vivaldi/1.0.344.37']","info","production","main","MISS","request","/.git/config","www.edge.stoneydsp.com","edge-n4snf8sov-stoneydsp.vercel.app","dpl_GbUnQUKgSdjoHbqd7aeBWj8yR2wX",0,"-",-1,0,"-","prj_bT56uU33xTH0U7kWw3rwu1lB2Ivj","edge"
"2023-09-23 13:29:53",1695475793000,"www.edge.stoneydsp.com/_all_dbs","GET",308,"z8xrf-1695475793054-43870067f363","['Mozilla/5.0 (l9scan/2.0.234313e21323e26373e26373; +https://leakix.net)']","info","production","main","MISS","request","/_all_dbs","www.edge.stoneydsp.com","edge-n4snf8sov-stoneydsp.vercel.app","dpl_GbUnQUKgSdjoHbqd7aeBWj8yR2wX",0,"-",-1,0,"-","prj_bT56uU33xTH0U7kWw3rwu1lB2Ivj","edge"
"2023-09-23 13:29:53",1695475793000,"www.edge.stoneydsp.com/s/234313e21323e26373e26373/_/;/META-INF/maven/com.atlassian.jira/jira-webapp-dist/pom.properties","GET",404,"9lnb6-1695475793102-7a6285964403","['Go-http-client/1.1']","warning","production","main","MISS","request","/404.html","www.edge.stoneydsp.com","edge-n4snf8sov-stoneydsp.vercel.app","dpl_GbUnQUKgSdjoHbqd7aeBWj8yR2wX",0,"-",-1,0,"-","prj_bT56uU33xTH0U7kWw3rwu1lB2Ivj","edge"
"2023-09-23 13:29:53",1695475793000,"www.edge.stoneydsp.com/ecp/Current/exporttool/microsoft.exchange.ediscovery.exporttool.application","GET",308,"ldrgc-1695475793015-a45155da9730","['Go-http-client/1.1']","info","production","main","MISS","request","/ecp/Current/exporttool/microsoft.exchange.ediscovery.exporttool.application","www.edge.stoneydsp.com","edge-n4snf8sov-stoneydsp.vercel.app","dpl_GbUnQUKgSdjoHbqd7aeBWj8yR2wX",0,"-",-1,0,"-","prj_bT56uU33xTH0U7kWw3rwu1lB2Ivj","edge"
"2023-09-23 13:29:53",1695475793000,"www.edge.stoneydsp.com/.git/config","GET",308,"r9jwz-1695475793091-beca94d91913","['Go-http-client/1.1']","info","production","main","MISS","request","/.git/config","www.edge.stoneydsp.com","edge-n4snf8sov-stoneydsp.vercel.app","dpl_GbUnQUKgSdjoHbqd7aeBWj8yR2wX",0,"-",-1,0,"-","prj_bT56uU33xTH0U7kWw3rwu1lB2Ivj","edge"
"2023-09-23 13:29:53",1695475793000,"www.edge.stoneydsp.com/.DS_Store","GET",308,"9lnb6-1695475793066-4efcbce4fcee","['Go-http-client/1.1']","info","production","main","MISS","request","/.DS_Store","www.edge.stoneydsp.com","edge-n4snf8sov-stoneydsp.vercel.app","dpl_GbUnQUKgSdjoHbqd7aeBWj8yR2wX",0,"-",-1,0,"-","prj_bT56uU33xTH0U7kWw3rwu1lB2Ivj","edge"
"2023-09-23 13:29:53",1695475793000,"www.edge.stoneydsp.com/.env","GET",308,"9lnb6-1695475793076-0df8215774e4","['Go-http-client/1.1']","info","production","main","MISS","request","/.env","www.edge.stoneydsp.com","edge-n4snf8sov-stoneydsp.vercel.app","dpl_GbUnQUKgSdjoHbqd7aeBWj8yR2wX",0,"-",-1,0,"-","prj_bT56uU33xTH0U7kWw3rwu1lB2Ivj","edge"
"2023-09-23 13:29:53",1695475793000,"www.edge.stoneydsp.com/telescope/requests","GET",308,"2wpsf-1695475793126-93d6f2b9954b","['Go-http-client/1.1']","info","production","main","MISS","request","/telescope/requests","www.edge.stoneydsp.com","edge-n4snf8sov-stoneydsp.vercel.app","dpl_GbUnQUKgSdjoHbqd7aeBWj8yR2wX",0,"-",-1,0,"-","prj_bT56uU33xTH0U7kWw3rwu1lB2Ivj","edge"
"2023-09-23 13:29:53",1695475793000,"www.edge.stoneydsp.com/login.action","GET",308,"lwjmc-1695475793041-2eb21bb0472f","['Go-http-client/1.1']","info","production","main","MISS","request","/login.action","www.edge.stoneydsp.com","edge-n4snf8sov-stoneydsp.vercel.app","dpl_GbUnQUKgSdjoHbqd7aeBWj8yR2wX",0,"-",-1,0,"-","prj_bT56uU33xTH0U7kWw3rwu1lB2Ivj","edge"
"2023-09-23 13:29:53",1695475793000,"www.edge.stoneydsp.com/config.json","GET",308,"bmknk-1695475793114-bb6b0138aab5","['Go-http-client/1.1']","info","production","main","MISS","request","/config.json","www.edge.stoneydsp.com","edge-n4snf8sov-stoneydsp.vercel.app","dpl_GbUnQUKgSdjoHbqd7aeBWj8yR2wX",0,"-",-1,0,"-","prj_bT56uU33xTH0U7kWw3rwu1lB2Ivj","edge"
"2023-09-23 13:29:53",1695475793000,"www.edge.stoneydsp.com/server-status","GET",308,"z8xrf-1695475793032-397f63794a88","['Go-http-client/1.1']","info","production","main","MISS","request","/server-status","www.edge.stoneydsp.com","edge-n4snf8sov-stoneydsp.vercel.app","dpl_GbUnQUKgSdjoHbqd7aeBWj8yR2wX",0,"-",-1,0,"-","prj_bT56uU33xTH0U7kWw3rwu1lB2Ivj","edge"
"2023-09-23 13:29:52",1695475792000,"www.edge.stoneydsp.com/.vscode/sftp.json","GET",308,"j78c4-1695475792924-c4a31834f4e4","['Go-http-client/1.1']","info","production","main","MISS","request","/.vscode/sftp.json","www.edge.stoneydsp.com","edge-n4snf8sov-stoneydsp.vercel.app","dpl_GbUnQUKgSdjoHbqd7aeBWj8yR2wX",0,"-",-1,0,"-","prj_bT56uU33xTH0U7kWw3rwu1lB2Ivj","edge"
"2023-09-23 13:29:52",1695475792000,"www.edge.stoneydsp.com/about","GET",308,"6zg26-1695475792936-b87ab89281bd","['Go-http-client/1.1']","info","production","main","MISS","request","/about","www.edge.stoneydsp.com","edge-n4snf8sov-stoneydsp.vercel.app","dpl_GbUnQUKgSdjoHbqd7aeBWj8yR2wX",0,"-",-1,0,"-","prj_bT56uU33xTH0U7kWw3rwu1lB2Ivj","edge"
"2023-09-23 13:29:52",1695475792000,"www.edge.stoneydsp.com/v2/_catalog","GET",404,"2vqbm-1695475792966-64005d54cef2","['Go-http-client/1.1']","warning","production","main","MISS","request","/404.html","www.edge.stoneydsp.com","edge-n4snf8sov-stoneydsp.vercel.app","dpl_GbUnQUKgSdjoHbqd7aeBWj8yR2wX",0,"-",-1,0,"-","prj_bT56uU33xTH0U7kWw3rwu1lB2Ivj","edge"
"2023-09-23 13:29:52",1695475792000,"www.edge.stoneydsp.com/debug/default/view","GET",308,"lwjmc-1695475792951-756b9b106fb7","['Go-http-client/1.1']","info","production","main","MISS","request","/debug/default/view","www.edge.stoneydsp.com","edge-n4snf8sov-stoneydsp.vercel.app","dpl_GbUnQUKgSdjoHbqd7aeBWj8yR2wX",0,"-",-1,0,"-","prj_bT56uU33xTH0U7kWw3rwu1lB2Ivj","edge"
"2023-09-23 13:29:50",1695475790000,"www.edge.stoneydsp.com/.git/config","GET",308,"25fcf-1695475790954-8bcfe7efede7","['Go-http-client/1.1']","info","production","main","MISS","request","/.git/config","www.edge.stoneydsp.com","edge-n4snf8sov-stoneydsp.vercel.app","dpl_GbUnQUKgSdjoHbqd7aeBWj8yR2wX",0,"-",-1,0,"-","prj_bT56uU33xTH0U7kWw3rwu1lB2Ivj","edge"
"2023-09-23 13:29:50",1695475790000,"www.edge.stoneydsp.com/.DS_Store","GET",308,"nt56n-1695475790491-a84beed4f2b9","['Go-http-client/1.1']","info","production","main","MISS","request","/.DS_Store","www.edge.stoneydsp.com","edge-n4snf8sov-stoneydsp.vercel.app","dpl_GbUnQUKgSdjoHbqd7aeBWj8yR2wX",0,"-",-1,0,"-","prj_bT56uU33xTH0U7kWw3rwu1lB2Ivj","edge"
"2023-09-23 13:29:50",1695475790000,"www.edge.stoneydsp.com/telescope/requests","GET",308,"9lnb6-1695475790998-ecb504a437bd","['Go-http-client/1.1']","info","production","main","MISS","request","/telescope/requests","www.edge.stoneydsp.com","edge-n4snf8sov-stoneydsp.vercel.app","dpl_GbUnQUKgSdjoHbqd7aeBWj8yR2wX",0,"-",-1,0,"-","prj_bT56uU33xTH0U7kWw3rwu1lB2Ivj","edge"
"2023-09-23 13:29:50",1695475790000,"www.edge.stoneydsp.com/.vscode/sftp.json","GET",308,"r8jzf-1695475790358-b44478dba887","['Go-http-client/1.1']","info","production","main","MISS","request","/.vscode/sftp.json","www.edge.stoneydsp.com","edge-n4snf8sov-stoneydsp.vercel.app","dpl_GbUnQUKgSdjoHbqd7aeBWj8yR2wX",0,"-",-1,0,"-","prj_bT56uU33xTH0U7kWw3rwu1lB2Ivj","edge"
"2023-09-23 13:29:50",1695475790000,"www.edge.stoneydsp.com/_all_dbs","GET",308,"bmknk-1695475790478-bf0ebfe7e438","['Mozilla/5.0 (l9scan/2.0.3393e21323e26373e26373; +https://leakix.net)']","info","production","main","MISS","request","/_all_dbs","www.edge.stoneydsp.com","edge-n4snf8sov-stoneydsp.vercel.app","dpl_GbUnQUKgSdjoHbqd7aeBWj8yR2wX",0,"-",-1,0,"-","prj_bT56uU33xTH0U7kWw3rwu1lB2Ivj","edge"
"2023-09-23 13:29:50",1695475790000,"www.edge.stoneydsp.com/debug/default/view","GET",308,"dhhd6-1695475790384-d0b8f7a4ec1f","['Go-http-client/1.1']","info","production","main","MISS","request","/debug/default/view","www.edge.stoneydsp.com","edge-n4snf8sov-stoneydsp.vercel.app","dpl_GbUnQUKgSdjoHbqd7aeBWj8yR2wX",0,"-",-1,0,"-","prj_bT56uU33xTH0U7kWw3rwu1lB2Ivj","edge"
"2023-09-23 13:29:50",1695475790000,"www.edge.stoneydsp.com/.env","GET",308,"r8jzf-1695475790504-ffebe9c5c915","['Go-http-client/1.1']","info","production","main","MISS","request","/.env","www.edge.stoneydsp.com","edge-n4snf8sov-stoneydsp.vercel.app","dpl_GbUnQUKgSdjoHbqd7aeBWj8yR2wX",0,"-",-1,0,"-","prj_bT56uU33xTH0U7kWw3rwu1lB2Ivj","edge"
"2023-09-23 13:29:50",1695475790000,"www.edge.stoneydsp.com/s/3393e21323e26373e26373/_/;/META-INF/maven/com.atlassian.jira/jira-webapp-dist/pom.properties","GET",404,"qjdkv-1695475790970-cb4f5c9f2a99","['Go-http-client/1.1']","warning","production","main","MISS","request","/404.html","www.edge.stoneydsp.com","edge-n4snf8sov-stoneydsp.vercel.app","dpl_GbUnQUKgSdjoHbqd7aeBWj8yR2wX",0,"-",-1,0,"-","prj_bT56uU33xTH0U7kWw3rwu1lB2Ivj","edge"
"2023-09-23 13:29:50",1695475790000,"www.edge.stoneydsp.com/about","GET",308,"fxrln-1695475790371-e85fb55be51a","['Go-http-client/1.1']","info","production","main","MISS","request","/about","www.edge.stoneydsp.com","edge-n4snf8sov-stoneydsp.vercel.app","dpl_GbUnQUKgSdjoHbqd7aeBWj8yR2wX",0,"-",-1,0,"-","prj_bT56uU33xTH0U7kWw3rwu1lB2Ivj","edge"
"2023-09-23 13:29:50",1695475790000,"www.edge.stoneydsp.com/server-status","GET",308,"l4qvg-1695475790448-b5dfe5f8c8f9","['Go-http-client/1.1']","info","production","main","MISS","request","/server-status","www.edge.stoneydsp.com","edge-n4snf8sov-stoneydsp.vercel.app","dpl_GbUnQUKgSdjoHbqd7aeBWj8yR2wX",0,"-",-1,0,"-","prj_bT56uU33xTH0U7kWw3rwu1lB2Ivj","edge"
"2023-09-23 13:29:50",1695475790000,"www.edge.stoneydsp.com/login.action","GET",308,"9d5jv-1695475790462-c51b7eb730f2","['Go-http-client/1.1']","info","production","main","MISS","request","/login.action","www.edge.stoneydsp.com","edge-n4snf8sov-stoneydsp.vercel.app","dpl_GbUnQUKgSdjoHbqd7aeBWj8yR2wX",0,"-",-1,0,"-","prj_bT56uU33xTH0U7kWw3rwu1lB2Ivj","edge"
"2023-09-23 13:29:50",1695475790000,"www.edge.stoneydsp.com/config.json","GET",308,"gxhcz-1695475790983-81201e956528","['Go-http-client/1.1']","info","production","main","MISS","request","/config.json","www.edge.stoneydsp.com","edge-n4snf8sov-stoneydsp.vercel.app","dpl_GbUnQUKgSdjoHbqd7aeBWj8yR2wX",0,"-",-1,0,"-","prj_bT56uU33xTH0U7kWw3rwu1lB2Ivj","edge"
"2023-09-23 13:29:50",1695475790000,"www.edge.stoneydsp.com/v2/_catalog","GET",404,"nt2r2-1695475790418-c4dad90f9c48","['Go-http-client/1.1']","warning","production","main","MISS","request","/404.html","www.edge.stoneydsp.com","edge-n4snf8sov-stoneydsp.vercel.app","dpl_GbUnQUKgSdjoHbqd7aeBWj8yR2wX",0,"-",-1,0,"-","prj_bT56uU33xTH0U7kWw3rwu1lB2Ivj","edge"
"2023-09-23 13:29:50",1695475790000,"www.edge.stoneydsp.com/ecp/Current/exporttool/microsoft.exchange.ediscovery.exporttool.application","GET",308,"ldrgc-1695475790434-88a7fba56c79","['Go-http-client/1.1']","info","production","main","MISS","request","/ecp/Current/exporttool/microsoft.exchange.ediscovery.exporttool.application","www.edge.stoneydsp.com","edge-n4snf8sov-stoneydsp.vercel.app","dpl_GbUnQUKgSdjoHbqd7aeBWj8yR2wX",0,"-",-1,0,"-","prj_bT56uU33xTH0U7kWw3rwu1lB2Ivj","edge"
```

Opened issue #40

**Comment by nathanjhood** [comment]
Wannabe-hackers be like...

**Pull request merged**
